name: CodeGuru Analysis and Upload Results

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  codeguru:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials for CodeGuru
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::008971672094:role/git_role
          aws-region: us-east-1

      # Step 3: Set up Node.js environment (if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Step 4: Trigger CodeGuru Reviewer to analyze the repository
      - name: Trigger CodeGuru Review
        run: |
          aws codeguru-reviewer create-code-review \
            --name CodeGuruReview_${{ github.sha }} \
            --repository-association-arn arn:aws:codeguru-reviewer:us-east-1:008971672094:association:59eb03ee-9a68-4478-9ea1-e22770a1fba6 \
            --type '{"RepositoryAnalysis": {"RepositoryHead": {"BranchName": "dev"}}}'

      # Step 5: Wait for CodeGuru Review to Complete
      - name: Wait for CodeGuru Review to Complete
        run: |
          echo "Waiting for CodeGuru review to complete..."
          sleep 130

      # Step 6: Get the Most Recent CodeGuru Review ARN
      - name: Get the Most Recent CodeGuru Review ARN
        id: get_arn
        run: |
          # Fetch the ARN of the most recent completed CodeGuru review
          REVIEW_ARN=$(aws codeguru-reviewer list-code-reviews \
            --query 'codeReviews[?state==`Completed`].codeReviewArn' \
            --output text | head -n 1)
          
          # Check if an ARN was found
          if [ -z "$REVIEW_ARN" ]; then
            echo "No CodeGuru review found."
            exit 1
          fi

          # Set the ARN as a GitHub Actions environment variable
          echo "REVIEW_ARN=$REVIEW_ARN" >> $GITHUB_ENV

      # Step 7: Fetch the CodeGuru Results
      - name: Fetch CodeGuru Results
        run: |
          if [ -z "${{ env.REVIEW_ARN }}" ]; then
            echo "No CodeGuru review ARN found. Exiting."
            exit 1
          fi

          aws codeguru-reviewer get-recommendations \
            --code-review-arn ${{ env.REVIEW_ARN }} \
            --output json > codeguru_results.json

      # Step 8: Commit the results back to the GitHub repository
      - name: Commit CodeGuru Results to GitHub
        run: |
          if [ -f codeguru_results.json ]; then
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add codeguru_results.json
            git commit -m "Add CodeGuru analysis results"
            git push origin ${{ github.ref }}
          else
            echo "File codeguru_results.json does not exist."
            exit 1
          fi

      # Step 9: Upload the results to GitHub as an artifact (optional)
      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeguru-results
          path: codeguru_results.json

      # Test 2-1
