name: Code Review with Hugging Face LLaMA or Claude

on:
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install requests

      # Step 4: Run the code review script
      - name: Review code using Hugging Face API
        env:
          HUGGING_FACE_API_KEY: ${{ secrets.HUGGING_FACE_API_KEY }} # Store in GitHub secrets
        run: |
          python src/huggingface_code_review.py

      # Step 5: Commit and push changes back to the repo
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated code corrections using Hugging Face" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


